name: ci
jobs:
  test:
    runs-on: ubuntu:22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        python -m pip install poetry
        poetry install
    - run: poetry run pytest